services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18083:80"

  chatbot_ui:
    build:
      context: ../shared/chatbot_ui
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - CHAT_COMPLETION_ENDPOINT=http://host.docker.internal:10000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./stellar_config.yaml:/app/stellar_config.yaml
