name: e2e stellar tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest-m
    defaults:
      run:
        working-directory: ./tests/stellar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: build stellar  docker image
        run: |
          cd ../../ && docker build  -f stellar /Dockerfile . -t stellarlaboratory/stellar

      - name: start stellar
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          docker compose up | tee &> stellar.logs &

      - name: wait for stellar to be healthy
        run: |
          source common.sh && wait_for_healthz http://localhost:10000/healthz

      - name: install poetry
        run: |
          export POETRY_VERSION=1.8.5
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: install test dependencies
        run: |
          poetry install

      - name: run stellar tests
        run: |
          poetry run pytest || tail -100 stellar.logs

      - name: stop stellar docker container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          docker compose down
